### ISSUE TITLE
Syntax error on loader.php

### ISSUE THREAD

**Issue by hfittipaldi** [juliopontes/joomla-override#10]
Hi, I'm using jomla 2.5.14 and when I activate the plugin, I get this error:

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in /my_address/plugins/system/joomlaoverride/core/loader.php on line 2

**Comment by juliopontes** [comment]
I've installed at 2.5.17 and not found any issues. Please open a new issue if this continue.

**Comment by iosoft** [comment]
I am facing the same issue. I am using Joomla! 2.5.20.
http://bit.ly/1klEeDb

I would like to request you to investigate on this.
I think its due to this anonymous function, but I am not sure....might be due to PHP version 5.2.17.

I have created a new ticket - https://github.com/juliopontes/joomla-override/issues/17
